let a = '250px';
console.log( Boolean(a) );
console.log( Number(a) );
let b = '0';
console.log( Number(b) );
console.log( Boolean(b) );
let c = '';
console.log( Boolean(c) );
console.log( Number(c) );
let d = '0.25';
console.log( Number(d) ); 
console.log( Boolean(d) );
let e = 'red18'; 
console.log( Boolean(e) );
console.log( Number(e) ); 
let f = null; 
console.log( Boolean(f) );
console.log( Number(f) ); 
let g = undefined;
console.log( Boolean(g) );
console.log( Number(g) ); 
